# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2022 Mikhail Zhilkin
#

name: CI_OpenWrt_22.03.0_mt7621_mtk_drv

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    env:
      images_dir: /opt/images
      owrt_branch: sercomm-22.03.0-propr
      owrt_config: https://downloads.openwrt.org/releases/22.03.0/targets/ramips/mt7621/config.buildinfo
      owrt_git: https://github.com/csharper2005/openwrt.git
      owrt_release: 22.03.0
      owrt_vermagic: 218bf6e00a546ab5c6ea465b29f9c777
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          sudo apt update
      - name: Set current datetime as env variable
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Download sources (OpenWrt)
        run: |
          echo ${{ env.current_date }}
          mkdir openwrt
          git clone --branch ${owrt_branch} ${owrt_git}
          cd openwrt/
      - name: Prepare build config
        run: |
          cd openwrt/
          wget ${owrt_config}
          echo 'CONFIG_BPF_TOOLCHAIN_NONE=y' >> config.buildinfo
          echo CONFIG_KERNEL_VERMAGIC=\"${owrt_vermagic}\" >> config.buildinfo
          sed -i '/CONFIG_ALL_NONSHARED/d' config.buildinfo
          sed -i '/CONFIG_BPF_TOOLCHAIN_BUILD_LLVM/d' config.buildinfo
          sed -i '/CONFIG_SDK_LLVM_BPF/d' config.buildinfo
          sed -i '/CONFIG_USE_LLVM_BUILD/d' config.buildinfo
          sed -i '/CONFIG_REPRODUCIBLE_DEBUG_INFO/d' config.buildinfo
          sed -i '/CONFIG_BPF_TOOLCHAIN_BUILD_LLVM/d' config.buildinfo
          sed -i '/CONFIG_HAS_BPF_TOOLCHAIN/d' config.buildinfo
          sed -i '/CONFIG_COLLECT_KERNEL_DEBUG/d' config.buildinfo
          sed -i '/CONFIG_SDK=y/d' config.buildinfo
          cp config.buildinfo .config
          cat .config
      - name: Install feeds
        run: |
          cd openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Make defconfig
        run: |
          cd openwrt/
          rm .config
          cp -r config.buildinfo .config
          make defconfig
      - name: Download sources (all)
        run: |
          cd openwrt/
          make download -j20
      - name: Build tools
        run: |
          cd openwrt/
          make tools/install -j$(nproc) V=s
      - name: Build toolchain
        run: |
          cd openwrt/
          make toolchain/install -j$(nproc) V=s
      - name: Build OpenWrt and packages
        run: |
          cd openwrt/
          make -j$(nproc) V=s || \
          make V=s
      - name: Create archive
        run: |
          image_name=OpenWrt_${owrt_release}_mt7621_mtk_drv_${{ env.current_date }}
          mkdir -p ${images_dir}/firmware/packages
          cd openwrt/
          mv bin/targets/ramips/mt7621/packages ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*beeline_smartbox-giga* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*beeline_smartbox-pro* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*beeline_smartbox-turbo* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*d-team_newifi-d2* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*wifire* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*xiaomi_redmi-router-ac2100* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*buildinfo* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*imagebuilder* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*manifest* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/profiles* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/sha256* ${images_dir}/firmware
          7z a -mx=9 ${images_dir}/${image_name}.7z ${images_dir}/firmware
          echo "image_name=${image_name}" >> $GITHUB_ENV
      - name: Upload images to Artifact
        if: ${{ github.event_name != 'release' && success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.image_name }}
          path:
            ${{ env.images_dir }}/${{ env.image_name }}.7z
