# SPDX-License-Identifier: GPL-2.0-or-later
#
# Copyright (c) 2023 Mikhail Zhilkin
#

name: CI_OpenWrt_22.03_mt7621_pending

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      images_dir: /opt/images
      owrt_branch: pending-22.03
      owrt_config: https://mirror-01.infra.openwrt.org/releases/22.03.6/targets/ramips/mt7621/config.buildinfo
      owrt_git: https://github.com/csharper2005/openwrt.git
      owrt_release: 22.03.6
      owrt_vermagic: b633bd997bdfdd50212c4c291cfee14e
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          sudo apt update
      - name: Set current datetime as env variable
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Download sources (OpenWrt)
        run: |
          echo ${{ env.current_date }}
          mkdir openwrt
          git clone --branch ${owrt_branch} ${owrt_git}
          cd openwrt/
      - name: Prepare build config
        run: |
          cd openwrt/
          wget ${owrt_config}
          echo 'CONFIG_BPF_TOOLCHAIN_NONE=y' >> config.buildinfo
          echo CONFIG_KERNEL_VERMAGIC=\"${owrt_vermagic}\" >> config.buildinfo
          sed -i '/CONFIG_ALL_NONSHARED/d' config.buildinfo
          sed -i '/CONFIG_BPF_TOOLCHAIN_BUILD_LLVM/d' config.buildinfo
          sed -i '/CONFIG_SDK_LLVM_BPF/d' config.buildinfo
          sed -i '/CONFIG_USE_LLVM_BUILD/d' config.buildinfo
          sed -i '/CONFIG_REPRODUCIBLE_DEBUG_INFO/d' config.buildinfo
          sed -i '/CONFIG_BPF_TOOLCHAIN_BUILD_LLVM/d' config.buildinfo
          sed -i '/CONFIG_HAS_BPF_TOOLCHAIN/d' config.buildinfo
          sed -i '/CONFIG_COLLECT_KERNEL_DEBUG/d' config.buildinfo
          sed -i '/CONFIG_SDK=y/d' config.buildinfo
          sed -i '/CONFIG_PACKAGE_luci-ssl=y/d' config.buildinfo
          echo 'CONFIG_PACKAGE_luci-ssl-openssl=y' >> config.buildinfo
          cp config.buildinfo .config
          cat .config
      - name: Install feeds
        run: |
          cd openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Make defconfig
        run: |
          cd openwrt/
          rm .config
          cp -r config.buildinfo .config
          make defconfig
      - name: Download sources (all)
        run: |
          cd openwrt/
          make download -j20
      - name: Build tools
        run: |
          cd openwrt/
          make tools/install -j$(nproc) V=s
      - name: Build toolchain
        run: |
          cd openwrt/
          make toolchain/install -j$(nproc) V=s
      - name: Build OpenWrt and packages
        run: |
          cd openwrt/
          make -j$(nproc) V=s || \
          make V=s
      - name: Create archive
        run: |
          cd openwrt/
          image_name=OpenWrt_${owrt_release}_mt7621_pending_${{ env.current_date }}
          7z a -mx=9 ${images_dir}/${image_name}.7z bin/targets/ramips/mt7621
          echo "image_name=${image_name}" >> $GITHUB_ENV
      - name: Upload images to Artifact
        if: ${{ github.event_name != 'release' && success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.image_name }}
          path:
            ${{ env.images_dir }}/${{ env.image_name }}.7z
