name: CI_OpenWrt_22.03.0-rc6_mt7621_Beeline_MTS_WiFire

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    env:
      images_dir: /opt/images
      owrt_branch: openwrt-22.03.0-rc6
      owrt_config: https://downloads.openwrt.org/releases/22.03.0-rc6/targets/ramips/mt7621/config.buildinfo
      owrt_git: https://github.com/csharper2005/openwrt.git
      owrt_release: 22.03.0-rc6
      owrt_vermagic: 050f210bd60063f7ec8f11931912635a
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          sudo apt update
      - name: Set current datetime as env variable
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Download sources (OpenWrt)
        run: |
          echo ${{ env.current_date }}
          mkdir openwrt
          git clone --branch ${owrt_branch} ${owrt_git}
          cd openwrt/
      - name: Prepare build config
        run: |
          cd openwrt/
          wget ${owrt_config}
          echo CONFIG_KERNEL_VERMAGIC=\"${owrt_vermagic}\" >> config.buildinfo
          sed -i '/CONFIG_ALL_NONSHARED/d' config.buildinfo
          cp config.buildinfo .config
          cat .config
      - name: Install feeds
        run: |
          cd openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Make defconfig
        run: |
          cd openwrt/
          rm .config
          cp -r config.buildinfo .config
          make defconfig
      - name: Download sources (packages)
        run: |
          cd openwrt/
          make download -j$(nproc)
      - name: Build OpenWrt and packages
        run: |
          cd openwrt/
          make V=s -j$(nproc)
      - name: Create archive
        run: |
          image_name=OpenWrt_${owrt_release}_mt7621_Beeline_MTS_WiFire_${{ env.current_date }}
          mkdir -p ${images_dir}/firmware/packages
          cd openwrt/
          mv bin/targets/ramips/mt7621/packages ${images_dir}/firmware/packages
          mv bin/targets/ramips/mt7621/*beeline* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*mts* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*wifire* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*buildinfo* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*imagebuilder* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*manifest* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/*sdk* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/profiles* ${images_dir}/firmware
          mv bin/targets/ramips/mt7621/sha256* ${images_dir}/firmware
          7z a -mx=9 ${images_dir}/${image_name}.7z ${images_dir}/firmware
          echo "image_name=${image_name}" >> $GITHUB_ENV
      - name: Upload images to Artifact
        if: ${{ github.event_name != 'release' && success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.image_name }}
          path:
            ${{ env.images_dir }}/${{ env.image_name }}.7z
